### PR TITLE
Docker-compose and Private Mail Fix (trying ...)

### PR DESCRIPTION
**Pull request by karesti**
This PR contains two commits 
- I'm using docker for redis and elastic search on my dev laptop. I'm sharing my docker-compose
- Try to fix private mailing conversations on google

### CODE REVIEW

**Comment by nicmarti** [comment]
That's a good idea. Would it be possible also to add a few lines in the README file so that someone with docker installed (as a pre-requisite) is able to use it? 
thanks Katia

**Comment by karesti** [comment]
@nicmarti I've changed the readme

**Comment by karesti** [comment]
@nicmarti I added the commit concerning the mail. I did not create a different PR

**Comment by nicmarti** [comment]
Thanks Katia for this PR

**Pull request merged**
