### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by aheritier**
I am not a UI guy but I tried a bit to improve some screens used by the speakers

# Speaker HomePage

## Before

Screenshot 2020-01-04 15 31 52

## After

Screenshot 2020-01-04 15 25 46

# Edit proposal

## Before

Screenshot 2020-01-04 15 32 08

## After

Screenshot 2020-01-04 15 28 03

# Edit co-speakers

## Before

Screenshot 2020-01-04 15 32 19

## After

Screenshot 2020-01-04 15 28 27

# Send Messages

## Before

Screenshot 2020-01-04 15 32 33

## After

Screenshot 2020-01-04 15 28 38

We could probably do more efforts in term of coherency but if we stop to use the app next year let's not do more than required

### CODE REVIEW

**Comment by aheritier** [comment]
cc @nicmarti @fcamblor

**Comment by fcamblor** [comment]
😍

**Comment by aheritier** [comment]
Few more updates @fcamblor @nicmarti  (I am stopping here)

# CFP Admin Home

Screenshot 2020-01-04 16 37 42


# Golden Tickets stats

Screenshot 2020-01-04 16 50 50


# Sponsors talks

Screenshot 2020-01-04 17 00 19


# All proposals
Screenshot 2020-01-04 17 41 53


# All votes
Screenshot 2020-01-04 18 26 07

**Comment by fcamblor** [comment]
@aheritier any chance you could cherry-pick commit d2703e3a4bc42391c9341d88c1453b47de0c0313 from [my repo](https://github.com/fcamblor/cfp-devoxx/commit/d2703e3a4bc42391c9341d88c1453b47de0c0313) ?

This would bring some better highlights for buttons changing type of proposal on `show votes` screen :
### Before
Image_05_01_2020_12_32_collée

### After
Votes_for_GVF-6534_aaaaaaa_-_Devoxx_France_2020

**Comment by aheritier** [comment]
I created PR #199 @fcamblor cc @nicmarti

**Pull request merged**
