### PR TITLE
Introducing Program Schedule

### PR DESCRIPTION
**Pull request by fcamblor**
This PR introduces a new data structure : Program Schedule

Program Schedule are aimed at fixing multiple issues in the CFP :
- Currently, we can't have a vision of which Slot Configuration are published or not
- We cannot have more than only 1 "published" schedule on the website

A new Devoxx Planner entry is added : "Manage current program"
Devoxx_Planner_-_Manage_current_program

This page allows to manage multiple Program Schedules, each referencing 0-1 slot configuration per proposal type :
Devoxx_Planner_-_Program_Schedules

Only 1 Program Schedule can be "Published" at a time : this will be the one Devoxx attendees will see on the website.
However, non-published Program schedules can be shared to some non-CFP admins simply by clicking the "private" schedule links : program schedule uuid will allow to show those schedule on the website without publishing it.
- Published schedule (with HoL and 2 quickies) :
Thursday_-_Published_schedule

- Private schedule (notice the URL, schedule don't have any HoL and some quickies are not added in the Slot Configuration as well)
Thursday_-_Private_Program_Schedule

Some buttons have been removed on the Slot Configuration screen, as they are now useless (there is no point at "publishing" a slot configuration now that we have Program Schedules)
Devoxx_Planner_-_Useless_Slot_Config_publishing
Slot_Configuration_-_no_buttons_anymore

At the beginning, when you don't have any Program Schedule defined, you will have some warning message that will tell you to create some :
Program_Schedules_-_Warnings
_Note that if no Program Schedule exists, nor is published, website schedule will fall back on an "empty" program schedule_

From a technical point of view :
- 2 Redis Collections have been created : `ProgramSchedules:DevoxxFR2020:Published` (String) and `ProgramSchedules:DevoxxFR2020` (Hashes)
New_Redis_collections

- Redis Collection `Published:Schedule` is now useless, and has thus been removed

- When a SlotConfiguration is updated in the background (example: when updated through sanity check), then the Published Program Schedule is automatically updated with the new Configuration Schedule key

- I deleted every show[WeekDayHERE].scala.html files, as I guess those templates are not used anymore (showOneDay is used instead)

### CODE REVIEW

**Comment by aheritier** [comment]
It's awesome @fcamblor 
Screenshot 2020-02-16 00 19 18
I tried it locally with the production data and it's working very well
I have not comment on the code itself.
For sure it's really a big improvement to share the agenda with the team and ease the management of the publication.
Playing with it I see only one improvement which could be useful: To see on the "Saved configuration" if a configuration is used in a program schedule - to be able to delete the unused ones (it's really the cherry on the top of the cake)

**Comment by aheritier** [comment]
@nicmarti if you could review this PR it could be really great. Thanks in advance

**Comment by fcamblor** [comment]
> Playing with it I see only one improvement which could be useful: To see on the "Saved configuration" if a configuration is used in a program schedule - to be able to delete the unused ones

True, will look into it

2 additionnal improvements I thought about : 
- allow to select a program schedule on the sanity check screen
- show when a slots config is not "the latest one" (from a latest modification chronological point of view) in a program schedule

**Comment by nicmarti** [comment]
Let me know when you want to deploy it

I can't really look at the code, but I appreciate the work. Thanks Fred.
It will be more practical than the slot publisher

Nicolas

**Comment by fcamblor** [comment]
@nicmarti @aheritier let me polish a bit the PR with the 3 identified improvements (should not take me too long I guess), then we'll deploy it

**Comment by fcamblor** [comment]
@aheritier added 3 improvements we talked about yesterday :

- Slot configurations are not deletable when they are part of a Program Schedule :
Non-Deletable_slot_configuration

- On Program Schedule, if we don't reference the "latest" Slot Configuration, then we have a warning icon
Program_Schedule_warning_for_slot_configs

- We can now select a Program Schedule on sanity check screen
Selectable_Program_Schedule_on_sanity_check_screen

_Note that some informations on that screen are *not* related to the Program Schedule (like the speaker & overall proposals checks)_

I also fixed some consistency checks regarding Program Schedule deletion : I was disabling delete button on published Program Schedule, but was not checking this rule serverside. It's now the case.

**Comment by fcamblor** [comment]
Added minor UI tweaks, allowing to display public schedule for published program schedule + fixed schedule button sizes
Devoxx_Planner

**Comment by aheritier** [comment]
It's X-Mas
It's awesome @fcamblor . Thanks a lot.
I tested it with our prod data and it is working fine
It's ok to deploy it it @nicmarti

**Pull request merged**
