### PR TITLE
Improve reviewer stats

### PR DESCRIPTION
**Pull request by fcamblor**
PR aimed at taking into consideration abstentions on Leaderboard graph because, yes, I'm sad to be in the latest reviewers currently :')
Leaderboard_Reviewers_-_Devoxx_France_2020

What has changed :
- Number of reviews take abstentions into consideration
- Bubble size is not based on points given, but on abstentions (the bigger your bubble is, the more abstentions you've given ... if you consider yourself as an ecclectic reviewer, then your goal is to have a smallest bubble as possible :-))
- Total points are not shown anymore, and are replaced by total of abstentions (that's how google chart is working, I cannot display total points anymore unfortunately :( )

As a completely unrelated note, I changed color for the "proceed to next proposal with different proposal type" button because it was green exactly like the "stay on the same proposal type" buttons :
- Regularly, when you still have proposal with same proposal type, you get :
Votes_for_HQP-6273_Domptez_le_travail_multibranche_avec_git_worktree___-_Devoxx_France_2020
- Once you don't have proposal anymore in current type, then you get :
Votes_for_TZS-7546_Le_1o1_outil_d_interaction_majeur_dans_votre_travail_-_Devoxx_France_2020
=> My proposal is to change latest screenshot to :
Votes_for_TZS-7546_Le_1o1_outil_d_interaction_majeur_dans_votre_travail_-_Devoxx_France_2020
It will impact reviewer's brain : "there is no green anymore, it means that something important is going to change on next review"

### CODE REVIEW

**Comment by aheritier** [comment]
I like the idea @fcamblor 
The size of the bubble based on the number of points given is redundant with the average you gave.
But there is a problem with abstentions, they are all considered at 0:


Screenshot 2020-01-21 17 22 23

:+1: The change for the color of the button of the next talk to review

**Comment by fcamblor** [comment]
@aheritier you need to trigger a refresh in the leader board in order to fill the new redis collection for abstentions
Leaderboard_-_Devoxx_France_2020

**Comment by aheritier** [comment]
@fcamblor HA HA HA, if you don't tell me everything ....

It's better

Screenshot 2020-01-21 17 37 24

All good for me @nicmarti

**Comment by fcamblor** [comment]
My bad, forgot to mention it :-)

pfff .. I'm still in the latest ones .... I need to find another way to cheat :-)

**Comment by nicmarti** [comment]
Nice one. I agree that bubble size = nb of Abstention is much more interesting. I'm a bit nervous when we play with LUA but from what I read, it seems to be correct.
Thanks again Fred for your contribution.

**Pull request merged**
