### PR TITLE
fix proposal to reviews list on my-votes screen

### PR DESCRIPTION
**Pull request by fcamblor**
Track filtering is not taken into consideration on the "total / total to review" numbers displayed on my votes screen :

All_my_votes_-_Devoxx_France_2020

All_my_votes_-_Devoxx_France_2020

### CODE REVIEW

**Review by aheritier — APPROVED** [review]
Oh yes you are right, I missed that one.
👍 

_What I would love to have is a badge on each button (type/track)  to see the number of reviews to do. I had a look but it's too complexe and requires to count all of them before every page thus it might kill the performances_

**Comment by fcamblor** [comment]
Agree on the badge, it would be nice

Disagree on the performance : [we fetch *every* remaining proposal already](https://github.com/nicmarti/cfp-devoxx/blob/dev/app/controllers/CFPAdmin.scala#L281), all we would have to do is group those remaining proposals by type (and maybe by track for current type to show the badge on both filters ;-))

I'll try to do this this noon, but in a separate PR (this is kind of "nice to have" improvement whereas current PR is aimed at fixing some bugs - we'll see if I'm quickier to submit the new PR than @nicmarti to deploy current PR on prod ;-))

**Comment by nicmarti** [comment]
Guys

Please be careful with performance and huge requests on Redis.
It might really slow down and decrease the user experience. That's why most
of the stats are computed async with a LUA script.
Nicolas

**Comment by fcamblor** [comment]
@nicmarti I didn't added a single Redis call during this PR (and #203)
Every reviews are loaded into a Scala list and we then work on it (in memory I assume) without making any additionnal call to Redis

I assume you wanted to comment on #208 instead of #206 ? :-)

**Comment by fcamblor** [comment]
closing as this issue is covered in #207

**Pull request closed without merging**
