### PR TITLE
Print friendly schedule

### PR DESCRIPTION
**Pull request by fcamblor**
This PR brings a totally reworked schedule, allowing to be printed on a single page.

Some improvements has been put onto the table in order to optimize space :
- Useless rooms are not displayed anymore by default (a query parameter allows to change this default .. but not sure if this will be really useful). What I call a "useless room" is a room not having a single talk inside it on the whole day.
- Too much `<td>` were generated on `break` slots, which was leading to a completely broken table (with different number of cells per rows)
- Timezone configuration has been centralized into the `ConferenceDescriptor` class ... some `Europe/Brussel` timezone was still used here and there
- Talks overlapping on multiple slots (typically : hands on labs) are now represented "visually" across multiple slots. End time is thus not displayed anymore for such talks.
- `favorite` (ugly) button picture has been replaced by ⭐️ (from font-awesome)
- Background color denotes talk's type (uni, conf etc..), meaning that it's now useless to display proposal type's label
- Using a dedicated icon to represent track, meaning that it's now useless to display track's label
- Rooms in header are now showing a hint for their location (particularly for Mezzanine rooms)
- Introduced a display flag allowing to either show every talk types on a given day, or hide BoFs talks, or display only BoFs talk (this is particularly useful for thursday where the schedule can be huge with the BoFs displayed)
- Fixed Labs' ending time (from 18:30 to 18:15) to match the reality. This was a misconfiguration bug in the `ConferenceDescriptor`. Note that this every slots' id is based on the start/end time, I preferred to keep the (old) id ending at 18:30 only for data backward compatibility ... otherwise, we would have a cluttered schedules and slot configurations (I know @aheritier don't have a lot of hair ... let's economize it :-) ). It means that for DevoxxFr 2021 we will have to remove this ugly hardcoded id.
- Displaying Schedule legends for both proposal types (background) and tracks (icons)

Note that there is an important change on the `Program Schedule` configuration : they now have a new field named `specificScheduleCSSSnippet` : this field allows to define specific width on every day/room.
Because this has to be finely adjusted depending on talk titles during the day.
I created a small JS snippet allowing to identify in realtime every cells that have the biggest height on every row in order to know which column to adjust first depending on the remaining pixels for total printable width.
This gist can be found here : https://gist.github.com/fcamblor/bec1cc6131564696fb12824f6ad3a842

⚠️ There is an Important breaking change that needs some migration performed prior to anything (otherwise, slots won't be reloadable from Redis).
It was due to `Rooms` case class being serialized inside each `Slot configuration`.
Making any change on this case class was failing deserialization (and obviously, I needed to make some tweaks on `Rooms`)
=> You will have to perform a `GET /schedulling/admin/migrateConfigs` as an administrator to migrate `Room` nodes to `roomId`, making a weak dependency between `Slot configuration` and `Room`s

### CODE REVIEW

**Comment by fcamblor** [comment]
PR is still in WIP, I still need to know if I should change the track icons, using the one defined by Devoxx BE (viewable [here](https://devoxx.be/talks-by-tracks/))]]

@aheritier if you want, we can organize a call tomorrow (or later this week) in order to share some knowledge on the way I "optimize" table width in `Program Schedules` as this is not something easy to explain textually :-)

**Comment by nicmarti** [comment]
Let me know when it's ready to merge

**Comment by aheritier** [comment]
it's awesome @fcamblor cc @nicmarti 
Feel free to ping me to chat about it.

> Fixed Labs' ending time (from 18:30 to 18:15) to match the reality. This was a misconfiguration bug in the ConferenceDescriptor. Note that this every slots' id is based on the start/end time, I preferred to keep the (old) id ending at 18:30 only for data backward compatibility ... otherwise, we would have a cluttered schedules and slot configurations (I know @aheritier don't have a lot of hair ... let's economize it :-) ). It means that for DevoxxFr 2021 we will have to remove this ugly hardcoded id.

I think there is a misunderstanding and the problem was with the visualization but it was accurate that our Thursday PM labs are from 3:30PM to 6:30PM (3H) and thus they finish when the last TiA starts and you cannot attend to the break before (excepted if the lab decides to finish early).

Otherwise I tested locally. I did a get on http://localhost:9000/schedulling/admin/migrateConfigs which returned an empty array. No error in logs. Schedules are empty

Screenshot 2020-02-26 09 06 36
Screenshot 2020-02-26 09 06 26
Screenshot 2020-02-26 09 06 47

We can review it together @fcamblor

**Comment by fcamblor** [comment]
@aheritier there was (still) a deserialization bug, I fixed it and pushed it alongside some improvements :-)

You should try to call `GET /schedulling/admin/migrateConfigs` once more (when you tried the first time, you got the error and nothing should have been migrated)

**Comment by aheritier** [comment]
http://localhost:9000/schedulling/admin/migrateConfigs is now ok and returns a lot of content

Then here is what it gives with the current agenda

[Wednesday - Devoxx France 2020.pdf](https://github.com/nicmarti/cfp-devoxx/files/4255614/Wednesday.-.Devoxx.France.2020.pdf)

[Thursday - Devoxx France 2020.pdf](https://github.com/nicmarti/cfp-devoxx/files/4255615/Thursday.-.Devoxx.France.2020.pdf)

[Friday - Devoxx France 2020.pdf](https://github.com/nicmarti/cfp-devoxx/files/4255616/Friday.-.Devoxx.France.2020.pdf)

FireShot Capture 009 - Wednesday - Devoxx France 2020 - localhost

FireShot Capture 010 - Thursday - Devoxx France 2020 - localhost

FireShot Capture 011 - Friday - Devoxx France 2020 - localhost

**Comment by fcamblor** [comment]
@aheritier looks good ... next step will be adjust column width using my script (that's where it will be easier to chat/talk about it rather than comment on github :-))

 On thursday, you can pass `showScheduleMode` query parameter to define what you want to be displayed :
- no value (default) or `showScheduleMode=ShowAll` : will show BoF alongside other talks
- `showScheduleMode=HideBOFs` : will show everything except BoFs
- `showScheduleMode=ShowOnlyBOFs` : will show only BoFs

Also, you can enable `print` rendering on chrome to show what is going to be printed during the print process.
In chrome, you can do it this way (I guess firefox will have a similar tooling) :
- Show `Rendering` tab in "more tools" menu
Rendering_tooling
- Enabling `print` mode
Enabling_print_mode

**Comment by fcamblor** [comment]
We've got a discussion with @aheritier and I noted following things...

**Quick wins**
- [x] Increase font size on regular (non-`print`) mode
- [x] Generalize time slot's `nowrap` (shouldn't be reserved to `print` mode)

**Must have**

- [x] Increase `fav` size and propose multiple UI for it (icon vs button, top vs bottom etc..)
- [x] Unify rendering for `Publisher.showAgendaByConfType` and `Publisher.showByDay()` (today, we have 2 types of rendering for both ... and filtering I did on `showByDay` could perfectly be applied on `showAgendaByConfType`, removing a lot of duplicated template code)

**Nice to have**

- [ ] See if showing `break`s on time slot column would be achievable (sharing same background/font), in order to clearly display that there is lunch during quickies on thursday/friday
- [x] Explore ways of making `english` badge more prominent, like replacing the icon with a "badge" (ideally, I'd see something like the ["beta" badge](https://codepen.io/nicklassandell/pen/wfmuB)) or adding a `[EN]` tag in the title
- [ ] Explore constraint programming ways of optimizing column width and font size while staying in the constrained width/height to have single-page prints
- [ ] Allow to overlap keynote talks over overflow rooms, in order to have a large width for such talks (and economize height compared to the `TBA` small talk title)

**Comment by aheritier** [comment]
It's very good @fcamblor 
I think we are good to merge this one. 
We can always improve in the incoming weeks
@nicmarti here is the result:

FireShot Capture 012 - Wednesday - Devoxx France 2020 - localhost

FireShot Capture 013 - Thursday - Devoxx France 2020 - localhost

FireShot Capture 014 - Friday - Devoxx France 2020 - localhost

(Don't forget to call `/schedulling/admin/migrateConfigs` after deploying the new version)

**Comment by aheritier** [comment]
(the small 0 in the right of my screenshots is due to ghostery, it's not something from Fred's code)

**Pull request merged**
