### PR TITLE
Implement watch, autowatch and digests features

### PR DESCRIPTION
**Pull request by fcamblor**
As a continuation of #254, this PR introduces multiple new features : 
- This is now possible to manually watch/unwatch a proposal
_CFP__MIR-6146_qweqweqwe_-_Devoxx_France_2022
_CFP__MIR-6146_qweqweqwe_-_Devoxx_France_2022

- The Autowatch preference is now triggered on different events : upon proposal submission and after any interaction on the proposal
- Digest email is now in place
- The existing Backoffice's "Email Digest" screen has been totally redesigned, allowing to simulate Digest email creation on a per-user basis
CFP_Admin_-_Email_Digests_Queue_-_Devoxx_France_2022

Technical implications : 
- For deserialization performances, I introduced a new `Events:V3:ForDigests` collection where I store digest-only events
- Given that every events are now handled with Digests, I removed all emails notifications (and `Comments:*:LastMessageId` collections)

How Digesting works : 
- Every Events appeared since latest Digest of same type are retrieved (for example, for daily digests, we retrieve every events created since yesterday)
- All proposals are extracted from these events
- All watchers are retrieved for these proposals
- For every watchers : 
    - Events are filtered : we keep only those concerning proposals where user is a watcher, we remove events where watcher is the initiator, we remove events not selected in watcher's notification preferences
    - We generate email content and send it to the watcher
    => It means that Digest emails are generated on a per-user basis
- Digest execution is then stored, so that next execution starts from this execution

There are only some minor things to do : 

- [x] I would like to maybe rework `Watcher` collection to store watching date, so that watcher are not notified on events created before their watching subscription
- [x] Avoid triggering auto-watch when vote=0 (abstention)
- [ ] ~Maybe transform `Events:V3*` collections to yearly collections (based on `ConferenceDescriptor`'s current year~

Note: This PR includes fixes from #258 : if this PR gets merged prior to current one, I'll rebase it

### CODE REVIEW

**Comment by nicmarti** [comment]
FYI for Redis collection name I prefer to always manually change them and not rely on the ConferenceDescriptor. For me, the storage life-cycle != the ConferenceDescriptor year value. This is why it is manually set in all models "by design"

**Review by aheritier — COMMENTED** [review]
Must be rebased due to changes on `dev`

**Comment by fcamblor** [comment]
@aheritier ✅

**Comment by fcamblor** [comment]
⚠️  I just pushed a fix to change `Watchers:<proposalId>`  from a Set to a SortedSet, in order to know when a user is starting to watch a proposal

This is intended to filter out events from digest when the event was created before Watcher subscribed to Proposal changes

=> It will need to del `Watchers:*` collections if you had some created locally (or in production) at the time you test this PR

**Comment by nicmarti** [comment]
I will also delete `Watchers:*` on prod before deploy

**Pull request merged**
