### PR TITLE
Deliberation quick fixes

### PR DESCRIPTION
**Pull request by fcamblor**
This PR brings a bunch of enhancements for the upcoming review meetings :-)

### Showing selected type & track, following other screens convention :
All_votes_-_Devoxx_France_2022

### URL change

URL is updated from `cfpadmin/allvotes/:confType?track=:track` to `cfpadmin/allvotes?confType=:confType&track=:track`
All_votes_-_Devoxx_France_2022
Notification_Center

### New buttons added to the UI to select `All` types or tracks : 
All_votes_-_Devoxx_France_2022

### Impacts on defaults

When not set : 
- confType is set to `uni` (before : was `all`)
- track default value is kept to `all`
=> this is done on purpose in order to decrease pressure on server "by default" when we navigate on this page

### New show columns checkboxes

Added some checkbox allowing to tell : 
- If we want to show GT average votes & Comitee+GT average votes - Default : **unchecked**
- If we want to show Track column - Default : **unchecked**, except if `all` track is selected
- If we want to show Proposal Type column - Default : **unchecked**, except if `all` type is selected
All_votes_-_Devoxx_France_2022

### New column for "my votes"

Introduced a new column showing current reviewer's vote on the proposal : this can be useful to show discrepancies with comitee vote (and to allow to sort table based on your votes, without having to navigate on another screen).
This column has to be enabled (this is disabled by default so that if someone shares his screen and navigates to this page, we don't see his votes by default :-) )
All_votes_-_Devoxx_France_2022

### New pre-calculated collection

To avoid too much impacts to retrieve current user's scores, I introduced a pre-calculated `Computed:ScoresForUser:<userId>` collection which is filled during scores computation job (executed every 10min)
=> Don't expect to see your votes in realtime on this screen, unless you trigger a manual recomputation.

When looking at local benchmarks, this additionnal call adds ~2ms to the execution (compared to 1-2 **seconds** for proposals loading)

## Showing colors on scores on allVotes screen

Displayed colored block around scores on : 
- Comitee average score
- GT average score
- GT+Comitee average score
- My vote
All_votes_-_Devoxx_France_2022

## Search field now looks not only in title, but also insummary content

I added proposals' summary in the datatable (on an hidden column) so that it gets indexed.

This grows : 
- all-talks (780 talks) page size from 2.8MB to 4.4MB (rendered in ~8s locally vs ~7s in prod currently)
- conferences talks (475 talks) page size from 1.7Mb to 2.7Mb (rendered in ~7s locally vs ~7s in prod currently)
- 100 talks page size from 376Kb to 580Kb (rendered in ~3.5s locally vs ~3.3s in prod currently)

## Misc

Fixed a bug when GT didn't cast any vote on a proposal : we were taking their vote in the GT+Comitee average score
All_votes_-_Devoxx_France_2022

### CODE REVIEW

**Comment by aheritier** [comment]
Thanks for the anonymisation of screenshots @fcamblor :-)
I tested it and it's working well but I noticed a bug on the new my votes column.
I tried to recompute the votes and in the logs I see:

```
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: ******* CFPAdmin allVotes for all and all
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: gathering all votes Ellapsed: 15.272544 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: gathering current user's votes Ellapsed: 0.999614 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: count approved talks Ellapsed: 0.73502 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: load and parse proposals Ellapsed: 101.960868 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: create list of Proposals Ellapsed: 89.927157 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: list to display Ellapsed: 0.001398 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: filter by track Ellapsed: 7.92E-4 ms
[debug] 16:12:06 [play-akka.actor.default-dispatcher-11] a.Benchmark: calculate remaining slots Ellapsed: 0.378804 ms
```

But I get:

Screenshot 2022-01-23 at 17 12 46

Everything else is working fine

It's sad that we use an old version of DataTables because there are some features (plugins) today to hide the columns, reorder them, export them and more ... 

Something a bit confusing (but it's always better like this than before) is that the options to show/hide the columns are reseted as soon as we click on type/track/recompute button (which is logic with the design we have)

**Comment by aheritier** [comment]
All good for me @fcamblor 
it's ready to be merged @nicmarti 
(SonarQube issues are relevant from my POV)

**Comment by fcamblor** [comment]
provided 2 fixes (first commit is simply a fixup matching your previous tests @aheritier) : 
- Putting back default value for `track` criteria to `all` (was: `java`, I edited my PR description accordingly)
- Fixed a bug where `Abs` / `10` values on "my votes" column was not sorted properly (it wasn't considered as integer values)

**Review by aheritier — APPROVED** [review]
Ok for me. Thanks @fcamblor 

Nice improvements

**Comment by aheritier** [comment]
Tested. It's ok for me

**Comment by fcamblor** [comment]
fixed a bug when we were searching in search field then resetting search field content (some columns were not well rendered)

\+ allowed to search into proposal summaries (added a section about this in the main post)

**Pull request merged**
