### PR TITLE
chore: Fix the play framework dependency on docker-compose.yml

### PR DESCRIPTION
**Pull request by eyal-lezmy**
The repository [alexproca/play:2.2.3](https://hub.docker.com/r/alexproca/play/) is not maintained anymore. And there is no alternative on Alex's profile.
[ifinavet/playframework:2.2.3](https://hub.docker.com/r/ifinavet/playframework/) does the same thing and seems pretty well organised.

### CODE REVIEW

**Comment by h3xstream** [comment]
This pull request fixes #85

**Comment by alexproca** [comment]
Since there is not a official build for play framework I created mine then forget is used here and deleted it. 

The replacement with [ifinavet/playframework](https://hub.docker.com/r/ifinavet/playframework/) will fix the problem for now but won't prevent the same think will happen in the future.

The fix would be to create a **play.dockerfile** and tell docker-compose to build play image based on some official image like **openjdk:7**

docker-compose.yml
```yaml
play:
    build:
      context: .
      dockerfile: play.dockerfile
    volumes:
      - .:/app:rw
    ports:
      - "9000:9000"
```

play.dockerfile
```Dockerfile
FROM openjdk:7

ENV PLAY_VERSION 2.2.6

RUN wget -q https://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip \
    && unzip -q play-${PLAY_VERSION}.zip \
    && rm play-${PLAY_VERSION}.zip \
    && ln -s /play-${PLAY_VERSION}/play /usr/local/bin/
```

**Comment by eyal-lezmy** [comment]
@alexproca thanks for the feedback. I'll try to update the PR asap.

**Comment by nicmarti** [comment]
Ok, @aheritier will do a review and merge it, thanks :-)

**Pull request merged**
